apiVersion: batch/v1
kind: CronJob

metadata:
  name: cronjob1
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cont1
              image: httpd
              command: ["/bin/sleep"]
              args: ["20"]
          restartPolicy: OnFailure
