apiVersion: v1
kind: Service
metadata:
  name: stssvc1
spec:
  ports:
  - port: 80
    targetPort: 80
  clusterIP: None
  selector:
    app: nginx


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts1
spec:
  serviceName: "stssvc1"
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: cont1
        image: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: www
          mountPath: /myvol1
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
